dist: xenial
addons:
  snaps:
  - name: node
    confinement: classic
    channel: 12
language: rust
rust:
  - stable
cache:
  cargo: true

before_install:
  - sudo ./scripts/install-tests.sh

before_script:
 - "cargo run"
 - sleep 10

script:
  - ./scripts/run-tests.sh
