dist: xenial
addons:
  snaps:
  - name: node
    confinement: classic
    channel: 12
language: rust
rust:
  - stable
cache:
  cargo: true

before_script:
 - "cargo run"
 - sleep 3s

install:
  - git submodule add https://github.com/JDSeiler/alexandria-tests

script:
  - pushd /home/travis/build/JDSeiler/alexandria-db/alexandria-tests && npm test
