dist: xenial
addons:
  snaps:
  - name: node
    confinement: classic
    channel: 12
language: rust
rust:
  - stable
cache:
  cargo: true

before_script:
 - cargo build
 - "cargo run &"
 - sleep 3s

install:
  - sudo apt-install sqlite3
  - git submodule add https://github.com/JDSeiler/alexandria-tests

script:
  - pushd /home/travis/build/JDSeiler/alexandria-db/alexandria-tests 
  - npm install
  - npm test
