dist: xenial
addons:
  snaps:
  - name: node
    confinement: classic
    channel: 12
language: rust
rust:
  - stable
cache:
  cargo: true

before_install:
  - ./scripts/install-tests.sh

script:
  - ./scripts/run-tests.sh
